# Open Review

Most of the text on this page is taken from [Matthew Salganik's](https://twitter.com/msalganik) [Open Review Toolkit Privacy and Consent page](http://www.bitbybitbook.com/en/privacy/)

Open Review means that you can freely read the book and easily help to make it better. You can offer suggestions by make annotations using [hypothes.is](https://hypothes.is/), an open source annotation system. Further, the website will be collecting your implicit feedback by tracking the readership and abandonment rate of each section of the book.

Open Review takes place at the same time as peer review. The feedback from Open Review and peer review will be used to create a revised manuscript. The Open Review period will end when the final manuscript is submitted to the publisher. 

## FAQ about open review

### What kind of feedback are you looking for?

Open Review is not just about catching typos. Rather, Open Review is designed to collect all types of feedback, and I'd particularly welcome any feedback that you have about the substance of the book. Are there sections that you find particularly confusing? Are their points that you find particularly important? Am I making claims that you think need to be refined? Are there parts of the book that you think should be removed? When in doubt, I think you should follow one of the main principles at Wikipedia: Be bold.

### Can I see the annotations that others are making?

Yes, all the annotations are public. You can see them on right hand side of the each page or you can read them in stream form.

### What are the benefits for readers?

You get to read the manuscript and help make it better.

### What are the benefits for authors and publishers?

The Open Review process will benefit both authors and publishers, even if they have no interest in increasing access to knowledge. The process will lead to higher manuscript quality through the explicit and implicit feedback. Further, the Open Review process will provide valuable data that can be used during that marketing of the book.

### Has anyone ever done something like this before?

This is based on [Matthew Salganik's](https://twitter.com/msalganik) [Open Review Toolkit](http://www.openreviewtoolkit.org/). He's written about some related efforts here: <http://www.bitbybitbook.com/en/open-review/>

### How I can learn more about traditional peer review of academic books?
The AAUP recently published [a report](http://www.aaupnet.org/resources/for-members/handbooks-and-toolkits/peer-review-best-practices) on best practices for peer review.

### Can I do this with my book?
Sure. Check out the code for this website at <https://www.github.com/benmarwick/aswr> for more about how we did it.

### I have a different question about Open Review. How can I get in touch?
Send an email to `bmarwick@uw.edu`

## Privacy and Consent Policy

### Overview

On this website, we are making the complete text of the book available at no cost. While you are reading the book, we are measuring reader behavior in aggregate. For example, we are measuring which sections of the book get read most often. This data will help us improve the book. Everything we are doing is common on modern websites. We describe it in more detail below.

### What information do we collect?

We use Google Analytics to collect information about how you interact with this website. Further, like most websites, we use cookies to enhance your experience, gather general visitor information, and track visits to our website. Please refer to the "do we use cookies?" section below for information about cookies and how we use them.

### How do we use your information?

Any of the information that we collect may be used for research, to improve the book, and to help sell the book.

### How do we protect your information?

We implement a variety of security measures to maintain the safety of the information that you provide us.

Most of the browsing information that we have is stored Google Analytics, and you can read more about their security and privacy principles.

Annotations that you add are managed by hypothes.is, and you can read more about their terms of service.

Our website is hosted by Github Pages, and you can read more about Github's terms of service.

### Do we use cookies?

Yes. Cookies are small files that a site or its service provider transfers to your computer's hard drive through your web browser (if you allow) that enables the sites or service providers systems to recognize your browser and capture and remember certain information.

In order to offer you a better site experience, we use cookies to understand and save your preferences for future visits and to compile aggregate data about site traffic.

### Do we disclose any information to outside parties?

We do not sell, trade, or otherwise transfer to outside parties your personally identifiable information except trusted third parties who assist us in operating our website, conducting research, or providing a service to you, so long as those parties agree to keep this information confidential. We may also release your information when we believe release is appropriate to comply with the law, enforce our site policies, or protect ours or others' rights, property, or safety.

### Third party links

Occasionally, at our discretion, we may include links to third party websites. These third party sites have separate and independent privacy policies. We, therefore, have no responsibility or liability for the content and activities of these linked sites. Nonetheless, we seek to protect the integrity of our site and welcome any feedback about these sites.

### Website hosting

Our website is hosted by Github Pages, and you can read more about Github's terms of service.

### Your consent

By using our site, you consent to our privacy policy.

### Questions

If you have any questions, please send us an email `bmarwick@uw.edu`

### Changes to our Privacy and Consent Policy

We reserve the right to change our privacy policy from time to time at our sole discretion. Please periodically check this section to review the current version of the Privacy and Consent Policy. All our previous policies are presented below, and we will continue to update this page if any changes are needed.
